#ifndef CRIPTOGRAFIA_HEXADECIMAL_H_INCLUDED
#define CRIPTOGRAFIA_HEXADECIMAL_H_INCLUDED
int tam_texto[100000];
void Criptografia_Hexadecimal(char Texto [100000],int CHAVE_PUBLICA);

#endif // CRIPTOGRAFIA_HEXADECIMAL_H_INCLUDED
